import 'dart:convert';
import 'dart:typed_data';

import 'dart:ui';

import 'package:umbra_flutter/umbra_flutter.dart';

/// {@template gradient_shader}
/// A Dart Shader class for the `gradient_shader` shader.
/// {@endtemplate}
class GradientShader extends UmbraShader {
  GradientShader._() : super(_cachedProgram!);

  /// {@macro gradient_shader}
  static Future<GradientShader> compile() async {
    try {
      // Caching the program on the first compile call.
      _cachedProgram ??= await FragmentProgram.compile(
        spirv: Uint8List.fromList(base64Decode(_spirv)).buffer,
      );

      return GradientShader._();
    } on Exception catch (err, stackTrace) {
      throw UmbraException(err, stackTrace);
    }
  }

  static FragmentProgram? _cachedProgram;

  Shader shader({
    required Size resolution,
    required double uTime,
    required double speed,
    required Vector2 uResolution,
  }) {
    return program.shader(
      floatUniforms: Float32List.fromList([
        uTime,
        speed,
        uResolution.x,
        uResolution.y,
        resolution.width,
        resolution.height,
      ]),
      samplerUniforms: [],
    );
  }
}

const _spirv =
    'AwIjBwAAAQAKAA0ARgAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ABwAEAAAABAAAAG1haW4AAAAANwAAAD4AAAAQAAMABAAAAAgAAAADAAMAAQAAAEABAAAEAAoAR0xfR09PR0xFX2NwcF9zdHlsZV9saW5lX2RpcmVjdGl2ZQAABAAIAEdMX0dPT0dMRV9pbmNsdWRlX2RpcmVjdGl2ZQAFAAQABAAAAG1haW4AAAAABQAHAA0AAABmcmFnbWVudCh2ZjI7dmYyOwAAAAUAAwALAAAAdXYAAAUABQAMAAAAZnJhZ0Nvb3JkAAAABQAGABAAAAB1X3Jlc29sdXRpb24AAAAABQAEACEAAABjb2xvcgAAAAUABAAoAAAAdV90aW1lAAAFAAMANQAAAHV2AAAFAAYANwAAAGdsX0ZyYWdDb29yZAAAAAAFAAUAOgAAAHJlc29sdXRpb24AAAUABAA+AAAAX0NPTE9SXwAFAAQAPwAAAHBhcmFtAAAABQAEAEEAAABwYXJhbQAAAAUABABFAAAAc3BlZWQAAABHAAMADQAAAAAAAABHAAMACwAAAAAAAABHAAMADAAAAAAAAABHAAMAEAAAAAAAAABHAAQAEAAAAB4AAAACAAAARwADABUAAAAAAAAARwADABgAAAAAAAAARwADABkAAAAAAAAARwADABwAAAAAAAAARwADAB0AAAAAAAAARwADACEAAAAAAAAARwADACUAAAAAAAAARwADACcAAAAAAAAARwADACgAAAAAAAAARwAEACgAAAAeAAAAAAAAAEcAAwApAAAAAAAAAEcAAwAqAAAAAAAAAEcAAwArAAAAAAAAAEcAAwAsAAAAAAAAAEcAAwAtAAAAAAAAAEcAAwAvAAAAAAAAAEcAAwAwAAAAAAAAAEcAAwAxAAAAAAAAAEcAAwAyAAAAAAAAAEcAAwA1AAAAAAAAAEcABAA3AAAACwAAAA8AAABHAAMAOgAAAAAAAABHAAQAOgAAAB4AAAADAAAARwADADsAAAAAAAAARwADAD4AAAAAAAAARwAEAD4AAAAeAAAAAAAAAEcAAwA/AAAAAAAAAEcAAwBAAAAAAAAAAEcAAwBBAAAAAAAAAEcAAwBEAAAAAAAAAEcAAwBFAAAAAAAAAEcABABFAAAAHgAAAAEAAAATAAIAAgAAACEAAwADAAAAAgAAABYAAwAGAAAAIAAAABcABAAHAAAABgAAAAIAAAAgAAQACAAAAAcAAAAHAAAAFwAEAAkAAAAGAAAABAAAACEABQAKAAAACQAAAAgAAAAIAAAAIAAEAA8AAAAAAAAABwAAADsABAAPAAAAEAAAAAAAAAAVAAQAEQAAACAAAAAAAAAAKwAEABEAAAASAAAAAAAAACAABAATAAAAAAAAAAYAAAArAAQAEQAAABYAAAABAAAAIAAEABoAAAAHAAAABgAAABcABAAfAAAABgAAAAMAAAAgAAQAIAAAAAcAAAAfAAAAKwAEAAYAAAAiAAAAAAAAACwABgAfAAAAIwAAACIAAAAiAAAAIgAAADsABAATAAAAKAAAAAAAAAArAAQABgAAAC4AAAAAAIA/IAAEADYAAAABAAAACQAAADsABAA2AAAANwAAAAEAAAA7AAQADwAAADoAAAAAAAAAIAAEAD0AAAADAAAACQAAADsABAA9AAAAPgAAAAMAAAA7AAQAEwAAAEUAAAAAAAAANgAFAAIAAAAEAAAAAAAAAAMAAAD4AAIABQAAADsABAAIAAAANQAAAAcAAAA7AAQACAAAAD8AAAAHAAAAOwAEAAgAAABBAAAABwAAAD0ABAAJAAAAOAAAADcAAABPAAcABwAAADkAAAA4AAAAOAAAAAAAAAABAAAAPQAEAAcAAAA7AAAAOgAAAIgABQAHAAAAPAAAADkAAAA7AAAAPgADADUAAAA8AAAAPQAEAAcAAABAAAAANQAAAD4AAwA/AAAAQAAAAD0ABAAJAAAAQgAAADcAAABPAAcABwAAAEMAAABCAAAAQgAAAAAAAAABAAAAPgADAEEAAABDAAAAOQAGAAkAAABEAAAADQAAAD8AAABBAAAAPgADAD4AAABEAAAA/QABADgAAQA2AAUACQAAAA0AAAAAAAAACgAAADcAAwAIAAAACwAAADcAAwAIAAAADAAAAPgAAgAOAAAAOwAEACAAAAAhAAAABwAAAEEABQATAAAAFAAAABAAAAASAAAAPQAEAAYAAAAVAAAAFAAAAEEABQATAAAAFwAAABAAAAAWAAAAPQAEAAYAAAAYAAAAFwAAAIgABQAGAAAAGQAAABUAAAAYAAAAQQAFABoAAAAbAAAACwAAABIAAAA9AAQABgAAABwAAAAbAAAAhQAFAAYAAAAdAAAAHAAAABkAAABBAAUAGgAAAB4AAAALAAAAEgAAAD4AAwAeAAAAHQAAAD4AAwAhAAAAIwAAAEEABQAaAAAAJAAAAAsAAAASAAAAPQAEAAYAAAAlAAAAJAAAAEEABQAaAAAAJgAAAAsAAAAWAAAAPQAEAAYAAAAnAAAAJgAAAD0ABAAGAAAAKQAAACgAAAAMAAYABgAAACoAAAABAAAADQAAACkAAAAMAAYABgAAACsAAAABAAAABAAAACoAAABQAAYAHwAAACwAAAAlAAAAJwAAACsAAAA+AAMAIQAAACwAAAA9AAQAHwAAAC0AAAAhAAAAUQAFAAYAAAAvAAAALQAAAAAAAABRAAUABgAAADAAAAAtAAAAAQAAAFEABQAGAAAAMQAAAC0AAAACAAAAUAAHAAkAAAAyAAAALwAAADAAAAAxAAAALgAAAP4AAgAyAAAAOAABAA==';
